Support forceBypass under armingModes
node-alarm-dot-com/homebridge-node-alarm-dot-com pull request #138
Opened 2024-11-29 03:01 UTC by DouweM

Closes https://github.com/node-alarm-dot-com/homebridge-node-alarm-dot-com/issues/76

2024-12-06 14:14 UTC, chase9 requested changes

2024-12-06 14:14 UTC, chase9 commented on README.md
> +  - Set mode Off/Heat/Cool/Auto
Could you remove this file from your PR? It rather not have whitespace changes in the merge. Thanks!

2024-12-06 14:14 UTC, chase9 commented
Thanks for submitting this! Could you remove the README changes since they're just whitespace, and also let me know if you have tested this on your own instance?

2024-12-08 15:52 UTC, DouweM commented
@chase9 Thanks for the review, I've removed the whitespace changes.

I've tested the forceBypass option directly on the API, but I didn't yet look into actually building and running and testing the plugin. What would be the easiest way to do that?

2024-12-11 21:29 UTC, DouweM commented
@chase9 I had a chance to test it and confirmed it works as expected!

2024-12-14 17:02 UTC, chase9 approved these changes

2024-12-14 18:17 UTC, chase9 commented
Great, looks good and thanks for the PR!

2024-12-14 18:17 UTC, merged